In [1]:
from datascience import *
import numpy as np

nba = Table.read_table('nba_salaries.csv').relabeled(3, 'SALARY')
debate = Table.read_table('debate.csv').sort('Candidate')

## Review ##

In [2]:
debate

Candidate        | Minutes Spoken | Words Spoken | Title
Amy Klobuchar    | 8.5            | 1,614        | Senator
Beto O'Rourke    | 10.3           | 1,932        | Representative
Bill de Blasio   | 5.6            | 881          | Mayor
Cory Booker      | 10.9           | 2,181        | Senator
Elizabeth Warren | 9.3            | 1,637        | Senator
Jay Inslee       | 5              | 875          | Governor
John Delaney     | 6.6            | 1,060        | Representative
Julián Castro    | 8.8            | 1,588        | Secretary
Tim Ryan         | 7.7            | 1,383        | Representative
Tulsi Gabbard    | 6.6            | 1,243        | Representative

In [3]:
debate.select('Candidate', "Words Spoken")

Candidate        | Words Spoken
Amy Klobuchar    | 1,614
Beto O'Rourke    | 1,932
Bill de Blasio   | 881
Cory Booker      | 2,181
Elizabeth Warren | 1,637
Jay Inslee       | 875
John Delaney     | 1,060
Julián Castro    | 1,588
Tim Ryan         | 1,383
Tulsi Gabbard    | 1,243

In [4]:
debate.drop("Title")

Candidate        | Minutes Spoken | Words Spoken
Amy Klobuchar    | 8.5            | 1,614
Beto O'Rourke    | 10.3           | 1,932
Bill de Blasio   | 5.6            | 881
Cory Booker      | 10.9           | 2,181
Elizabeth Warren | 9.3            | 1,637
Jay Inslee       | 5              | 875
John Delaney     | 6.6            | 1,060
Julián Castro    | 8.8            | 1,588
Tim Ryan         | 7.7            | 1,383
Tulsi Gabbard    | 6.6            | 1,243

In [6]:
debate.sort('Minutes Spoken', descending = True)

Candidate        | Minutes Spoken | Words Spoken | Title
Cory Booker      | 10.9           | 2,181        | Senator
Beto O'Rourke    | 10.3           | 1,932        | Representative
Elizabeth Warren | 9.3            | 1,637        | Senator
Julián Castro    | 8.8            | 1,588        | Secretary
Amy Klobuchar    | 8.5            | 1,614        | Senator
Tim Ryan         | 7.7            | 1,383        | Representative
Tulsi Gabbard    | 6.6            | 1,243        | Representative
John Delaney     | 6.6            | 1,060        | Representative
Bill de Blasio   | 5.6            | 881          | Mayor
Jay Inslee       | 5              | 875          | Governor

In [7]:
debate.where('Title', are.equal_to('Senator'))

Candidate        | Minutes Spoken | Words Spoken | Title
Amy Klobuchar    | 8.5            | 1,614        | Senator
Cory Booker      | 10.9           | 2,181        | Senator
Elizabeth Warren | 9.3            | 1,637        | Senator

In [11]:
low_speakers = debate.where('Minutes Spoken', are.below(6))
low_speakers

Candidate      | Minutes Spoken | Words Spoken | Title
Bill de Blasio | 5.6            | 881          | Mayor
Jay Inslee     | 5              | 875          | Governor

In [9]:
debate

Candidate        | Minutes Spoken | Words Spoken | Title
Amy Klobuchar    | 8.5            | 1,614        | Senator
Beto O'Rourke    | 10.3           | 1,932        | Representative
Bill de Blasio   | 5.6            | 881          | Mayor
Cory Booker      | 10.9           | 2,181        | Senator
Elizabeth Warren | 9.3            | 1,637        | Senator
Jay Inslee       | 5              | 875          | Governor
John Delaney     | 6.6            | 1,060        | Representative
Julián Castro    | 8.8            | 1,588        | Secretary
Tim Ryan         | 7.7            | 1,383        | Representative
Tulsi Gabbard    | 6.6            | 1,243        | Representative

## Numbers ##

In [12]:
30 #int

30

In [13]:
30.0 #float

30.0

In [14]:
30 * 30

900

In [16]:
30.5 * 3

91.5

In [17]:
50/17

2.9411764705882355

In [18]:
50/10

5.0

In [19]:
10 ** 3

1000

In [20]:
10 ** 3.0

1000.0

In [21]:
10 ** 0.5

3.1622776601683795

In [22]:
1234567.8218427638471623987468213 - 1234567.821842763847162

0.0

In [23]:
1234567.8218427638471623987468213

1234567.8218427638

In [24]:
(13 ** 0.5) ** 2 #floating point errors

12.999999999999998

In [25]:
10 / 5

2.0

In [26]:
int(10/5)

2

In [27]:
int(10/4)

2

In [28]:
float(3)

3.0

In [29]:
6/4000000000000000000000

1.5e-21

In [30]:
2.5e-3

0.0025

## Strings ##

In [31]:
debate.select("Title")

Title
Senator
Representative
Mayor
Senator
Senator
Governor
Representative
Secretary
Representative
Representative

In [33]:
debate.select(Title)

NameError: name 'Title' is not defined

In [34]:
label = "Title"

In [35]:
debate.select(label)

Title
Senator
Representative
Mayor
Senator
Senator
Governor
Representative
Secretary
Representative
Representative

In [36]:
"Candidate"

'Candidate'

In [37]:
'Candidate'

'Candidate'

In [38]:
'Beto O'Rourke'

SyntaxError: invalid syntax (<ipython-input-38-193bbd20e861>, line 1)

In [39]:
"Beto O'Rourke"

"Beto O'Rourke"

In [40]:
"y'all"

"y'all"

In [41]:
debate.where("Candidate", are.equal_to("Beto O'Rourke"))

Candidate     | Minutes Spoken | Words Spoken | Title
Beto O'Rourke | 10.3           | 1,932        | Representative

In [42]:
"straw" + "berry"

'strawberry'

In [45]:
"Dwinelle "+ "Hall"

'Dwinelle Hall'

In [46]:
len(label)

5

In [47]:
label

'Title'

In [53]:
length_of_strawberry = len("strawberry")

In [49]:
'omg'.upper()

'OMG'

In [50]:
len

<function len(obj, /)>

In [51]:
len(make_array(1,2,3))

3

In [52]:
3.upper()

SyntaxError: invalid syntax (<ipython-input-52-24f0ec1487a0>, line 1)

In [54]:
length_of_strawberry

10

In [55]:
x = 3
y = '4'
z = '5.6'

In [56]:
x + y

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [60]:
int('45.6')

ValueError: invalid literal for int() with base 10: '45.6'

In [58]:
x + int(y + z)

ValueError: invalid literal for int() with base 10: '45.6'

In [61]:
str(x) + int(y)

TypeError: must be str, not int

## Types ##

In [62]:
type(3)

int

In [63]:
type(3.0)

float

In [64]:
a = 10

In [65]:
type(a)

int

In [66]:
type('abc')

str

In [67]:
type(debate)

datascience.tables.Table

In [68]:
type(abs)

builtin_function_or_method

In [69]:
7 < 8

True

In [70]:
7 > 8

False

In [71]:
7 >= 7

True

In [72]:
7 == 7

True

In [73]:
7 != 7

False

In [74]:
type(7==7)

bool

In [75]:
True

True

## Arrays ##

In [76]:
make_array(16, 3, 4, 35)

array([16,  3,  4, 35])

In [77]:
groceries = make_array(16, 3, 4, 35)

In [78]:
make_array('apples', 'milk', 'bread', 'beans')

array(['apples', 'milk', 'bread', 'beans'], dtype='<U6')

In [79]:
bad_time = make_array(1,2,3,'hi')
bad_time

array(['1', '2', '3', 'hi'], dtype='<U21')

In [82]:
discounted_groceries = groceries - 2
discounted_groceries

array([14,  1,  2, 33])

In [83]:
groceries * 0.2

array([3.2, 0.6, 0.8, 7. ])

In [84]:
groceries - (groceries * 0.2)

array([12.8,  2.4,  3.2, 28. ])

In [85]:
coupon = make_array(0.2, 0.1, 0.3, 0.25)

In [86]:
groceries * coupon

array([3.2 , 0.3 , 1.2 , 8.75])

In [87]:
groceries * make_array(0.2, 0.1, 0.3)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [88]:
sum(groceries)

58

## NumPy ##

In [89]:
import numpy as np

In [90]:
np.average(groceries)

14.5

In [91]:
np.diff(groceries)

array([-13,   1,  31])

## Columns of Tables are Arrays ##

In [92]:
debate

Candidate        | Minutes Spoken | Words Spoken | Title
Amy Klobuchar    | 8.5            | 1,614        | Senator
Beto O'Rourke    | 10.3           | 1,932        | Representative
Bill de Blasio   | 5.6            | 881          | Mayor
Cory Booker      | 10.9           | 2,181        | Senator
Elizabeth Warren | 9.3            | 1,637        | Senator
Jay Inslee       | 5              | 875          | Governor
John Delaney     | 6.6            | 1,060        | Representative
Julián Castro    | 8.8            | 1,588        | Secretary
Tim Ryan         | 7.7            | 1,383        | Representative
Tulsi Gabbard    | 6.6            | 1,243        | Representative

In [ ]:
debate.select('Candidate')

In [94]:
type(debate.select('Candidate'))

datascience.tables.Table

In [95]:
debate.column("Candidate")

array(['Amy Klobuchar', "Beto O'Rourke", 'Bill de Blasio', 'Cory Booker',
       'Elizabeth Warren', 'Jay Inslee', 'John Delaney', 'Julián Castro',
       'Tim Ryan', 'Tulsi Gabbard'], dtype='<U16')

In [ ]:
type(debate.column("Candidate"))

In [96]:
np.average(debate.column('Minutes Spoken'))

7.93

In [97]:
debate.column('Words Spoken') / debate.column('Minutes Spoken')

array([189.88235294, 187.57281553, 157.32142857, 200.09174312,
       176.02150538, 175.        , 160.60606061, 180.45454545,
       179.61038961, 188.33333333])

In [98]:
groceries.item(0)

16

In [99]:
groceries.item(4)

IndexError: index 4 is out of bounds for axis 0 with size 4

In [100]:
debate.column('Minutes Spoken').item(1)

10.3

In [107]:
type(groceries)

numpy.ndarray

## Ranges ##

In [101]:
make_array(1,2,3,4,5,6,7,8,9,10)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
np.arange(60)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [103]:
np.arange(1,61)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [104]:
np.arange(5,500,3)

array([  5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35,  38,  41,
        44,  47,  50,  53,  56,  59,  62,  65,  68,  71,  74,  77,  80,
        83,  86,  89,  92,  95,  98, 101, 104, 107, 110, 113, 116, 119,
       122, 125, 128, 131, 134, 137, 140, 143, 146, 149, 152, 155, 158,
       161, 164, 167, 170, 173, 176, 179, 182, 185, 188, 191, 194, 197,
       200, 203, 206, 209, 212, 215, 218, 221, 224, 227, 230, 233, 236,
       239, 242, 245, 248, 251, 254, 257, 260, 263, 266, 269, 272, 275,
       278, 281, 284, 287, 290, 293, 296, 299, 302, 305, 308, 311, 314,
       317, 320, 323, 326, 329, 332, 335, 338, 341, 344, 347, 350, 353,
       356, 359, 362, 365, 368, 371, 374, 377, 380, 383, 386, 389, 392,
       395, 398, 401, 404, 407, 410, 413, 416, 419, 422, 425, 428, 431,
       434, 437, 440, 443, 446, 449, 452, 455, 458, 461, 464, 467, 470,
       473, 476, 479, 482, 485, 488, 491, 494, 497])

In [106]:
type(np.arange(6))

numpy.ndarray

In [108]:
six_array = np.arange(6)

In [109]:
six_array

array([0, 1, 2, 3, 4, 5])